### ISSUE TITLE
Deletion of Page Fails

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#458]
When trying to delete a page by adding the correct keyword as confirmation I see a flash of a modal window which might include the word error but it is hard to say because it disappears very fast.

If the wrong keyword is entered a modal window appears, which states that the page could not be removed.

In both cases, the page is not deleted.

**Comment by moiri** [comment]
Side note: I think it would make more sense to ask for the `keyword` of the page not the `name` in the delete confirmation modal window. Otherwise it might be confused with the title of the page.

**Comment by Kodzhabashev** [comment]
Implemented in v6.11.0
