### ISSUE TITLE
Items Inside a Link can only be Moved as a Whole

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#459]
When trying to move children of children of a link, always the immediate child of the link is selected for moving.

In the following example I grabbed section `1708718129-image_1709328504_1709328983`
![Screenshot from 2024-03-01 23-13-38](https://github.com/humdek-unibe-ch/sh-selfhelp/assets/1411723/3cf445d7-a01c-4500-9215-c01d595a5e7b)

**Comment by moiri** [comment]
I just noticed, that it is also no longer possible to select child items of a link:

When clicking on the eye symbol, an error modal with the message `something went wrong` flashes quickly and the page is reloaded (maybe?)

**Comment by Kodzhabashev** [comment]
Fixed in v6.11.0

**Comment by Kodzhabashev** [comment]
Duplication of #375
