### ISSUE TITLE
A simple List Style is Missing

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#460]
A style to create a simple `<ul><li></li></ul>` list is missing (`ul` would be the container and `li` the child items).

This could help to create a card kitchen sink (https://getbootstrap.com/docs/4.1/components/card/#kitchen-sink) in combination with the entry list.

**Comment by moiri** [comment]
It might be a better option to offer this as a style choice for the entry list (similar to the `load_as_table` property)

**Comment by Kodzhabashev** [comment]
Maybe we can add a custom tag style, where the user can select in a drop down what tag is loaded. It should have children.

**Comment by Kodzhabashev** [comment]
I think that style could be with these tags:

- `<ul>` Defines an unordered list.
- `<ol>` Defines an ordered list.
- `<li>` Defines a list item.
- `<table>` Defines a table.
- `<tr>` Defines a row in a table.
- `<td>` Defines a cell in a table.
- `<th>` Defines a header cell in a table.

**Comment by Kodzhabashev** [comment]
Implemented in v6.11.0
