### ISSUE TITLE
Nested Entry Lists

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#461]
I want to use nested entry lists that point to their corresponding entry records.

The URL of parent entry record page is `my_parent_record/[i:record_id]?`.

I would like to create an URL for the child entry list that reflects this hierarchy. How would I do this?
I tried `my_parent_record/[i:p_record_id]/my_child_record/[i:record_id]?` but this does not work.

**Comment by moiri** [comment]
Ok, this does not seem to be possible right now as URLs are rather rigid.
This would be cool if possible, though.

However, this feels like a lot of work to support something like this, given that an easy workaround is to just not use hierarchical URLs,

**Comment by moiri** [comment]
If this is a thing for the future it might make more sense to change the record prefix to something configurable.

**Comment by Kodzhabashev** [comment]
### New features
 - #461 - add field `url_param` to style `entryRecord` - The `url_param` field specifies the name of the URL parameter that will be extracted from the URL. This parameter is utilized to filter the form based on the `record_id` and return a single entry. When the specified URL parameter is present in the URL, its value is used as the `record_id` to fetch the corresponding entry from the database. This allows for dynamic filtering of the form entries based on the value provided in the URL.
 - #461 - add field `scope` to styles `entryRecord`, `entryList` and `loop`. The 'scope' field serves as a prefix for variable naming within the context of the style. If set, it is appended to the beginning of variable names, allowing for better organization and distinction of variables within the style. For example, if the 'scope' is set to "item", variables within the style will be prefixed with "item_", such as "item_title", "item_description", etc. Using a scope helps to avoid naming conflicts and provides clarity in variable usage within the style.
 - #461 - add as global variables all parameters that comes form the URL. The parameters variable name is with prefix and suffix `__`. Example for URL: `/nested/[i:main_id]/[i:sub_id]` will generate global parameters: `__main_id__` and `__sub_id__`

In v6.11.0 all this could be achieved
