### ISSUE TITLE
A Style to Render Localised Dates and Time

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#473]
A style which is capable of rendering a data entry stored with a `date`, `time` or `datetime` input field as localized time string in the selected language.

e.g. 2024-03-15 should be rendered as "Freitag 15. März 2024".

Preferably the rendered string should be configurable.

**Comment by Kodzhabashev** [comment]
I can check if it is possible to use the PHP math function FormulaParser plugin to set the locale based on the user selected language.

**Comment by Kodzhabashev** [comment]
This was added in FormulaParser plugin v1.5.6
