### ISSUE TITLE
Image Style needs Width and Height Properties

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#474]
The style `image` is missing the properties `width` and `height`.

It might also be useful to add further available `<img>` attributes.

**Comment by Kodzhabashev** [comment]
Add fields, width and height numbers. It is always pixels

**Comment by Kodzhabashev** [comment]
Add new field img_src with display 1, it is a content field. Set the value to the current source fields and then remove the source fields. The source field is also used in ShowUserInputForm

**Comment by Kodzhabashev** [comment]
Added in v7.0.0
