### ISSUE TITLE
Style MarkdownInline Acts Weird when using HTML

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#477]
When using HTML tags in the style `markdownInline` the CMS input field renders the value in a weird way.

![Screenshot from 2024-04-01 23-17-15](https://github.com/humdek-unibe-ch/sh-selfhelp/assets/1411723/2858a94e-0de0-4802-8cdc-201af64320e6)

When saving, only the part which is inside the input field is stored.

The actual value is `<i class="fas fa-clock"></i> {{date_time}}`

**Comment by Kodzhabashev** [comment]
Fixed in v6.13.0
