### ISSUE TITLE
Multi-Page Form

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#484]
I would like to have a 2-step form where in a fist step information must be filled in and in a second step, the information must be verified.

It should be possible to:
- go back from the verification page to the information page to change entries
- enter the information as a guest (i.e. the data cannot be persisted by user id)
- fill in the two-step multiple times starting from an empty form

Is there a way of achieving this?

**Comment by Kodzhabashev** [comment]
I did not fully understand what you need, but I think maybe survey-js plugin could be the easiest way to achieve this?

**Comment by moiri** [comment]
Yes, I guess with survey-js I could achieve this.
I am not entirely happy with this but we can close the issue for now.
