### ISSUE TITLE
Request for Dark Mode Support

### ISSUE THREAD

**Issue by NS21fpsy** [humdek-unibe-ch/sh-selfhelp#489]
Hi Stefan

Dark mode support, especially for smartphones, has been requested on a number of occasions.

In particular, many smartphone users have their phones set to dark mode. This can lead to rendering problems, as I have experienced with my Xiaomi's dark mode. For example, texts were no longer recognisable.

Thanks

**Comment by Kodzhabashev** [comment]
Added in v7.1.0
