### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by NS21fpsy** [humdek-unibe-ch/sh-selfhelp#496]
![image](https://github.com/humdek-unibe-ch/sh-selfhelp/assets/79153609/26a67912-c463-4be0-b95d-b8e45308f1cd)

Project: dropit.psy.unibe.ch

On the "Verlauf"-page, we work with the user name: https://dropit.psy.unibe.ch/W-01 

This username has a special character but it is not rendered as expected, see the image.

**Comment by Kodzhabashev** [comment]
This should be fixed in v6.17.0
