### ISSUE TITLE
Textfield not working.

### ISSUE THREAD

**Issue by WayerLiu** [humdek-unibe-ch/sh-selfhelp#506]
In a structure of formUserInputRecord - text area, the text field is not working on some devices or platforms. Some cases users are able to click, edit, and submit, but in cases such as some android phone and some web browsers, users cannot do so.

**Comment by Kodzhabashev** [comment]
This is for selfhelp app and it happened when inside the form there are other elements and then in these elements there are inputs.

**Comment by Kodzhabashev** [comment]
https://github.com/humdek-unibe-ch/sh-selfhelp_app/issues/25

Fixed in app v3.4.2
