### ISSUE TITLE
Overwriting variables to address a specific user

### ISSUE THREAD

**Issue by NS21fpsy** [humdek-unibe-ch/sh-selfhelp#511]
Extend the ‘overwrite variables’ functionality (especially in Form Action Builder) so that a study manager or an experimenter can, for example, save the results of a telephone interview with a participant and the jobs in Form Builder are then carried out **for the participant** (and not for the experimenter).

For example, ‘add group survey_done immediately’ is then carried out for the participant and not for the experimenter.

In the DB, the result of the experimenter's form can remain with the experimenter, we simply have a reference to the participant involved, e.g. we call the variable ‘target user code’.

**Comment by Kodzhabashev** [comment]
Implemented in v7.0.19
